name: Documentation
on:
  release:
    types:
    - created
jobs:
  docs:
    name: Documentation builds
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Pip cache
        uses: actions/cache@v3
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-1
      - name: Set up Nox
        uses: excitedleigh/setup-nox@v2.1.0
      - name: Build docs
        run: nox -s docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          cname: bridgekeeper.leigh.party
